{% set name = "underworld2" %}
{% set version = "2.10.0b" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
    #git_url: https://github.com/underworldcode/underworld2.git
    #git_tag: conda_deploy
    path: ../.

build:
  number: 0
  #script: python -m pip install -vvv --no-deps --ignore-installed --prefix=$PREFIX .

requirements:
  build:
    - {{ mpi }}
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config

  host:
    - libxml2
    - swig>=4.0.0
    - scons>=3.0.0
    - h5py=*=mpi*
    - mpi4py
    - petsc==3.13
    - python
    - pip

  run:
    - python
    - six
    - numpy>=1.18.1
    - petsc==3.13
    - mpi4py
    - scipy>=1.4.1
    - h5py=*=mpi*


about:
  home: "https://github.com/underworldcode/underworld2"
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "Geodynamics API"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - rbeucher
    - jmansour
    - jgiordani
    - lmoresi
