{% set name = "underworld2" %}
{% set version = "2.10.0b" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/underworldcode/underworld2.git
  git_tag: conda_deploy

build:
  number: 0

requirements:
  build:
    - {{ mpi }}
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - libxml2
    - pkg-config
    - swig>=4.0.0
    - scons>=3.0.0
    - petsc==3.13
    - numpy>=1.18.1
    - h5py=*=mpi*
    - mpi4py

  host:
    - python
    - pip
    - numpy>=1.18.1
    - scipy>=1.4.1

  run:
    - python
    - numpy x.x


about:
  home: "https://github.com/underworldcode/underworld2"
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "Geodynamics API"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - rbeucher
    - jmansour
    - jgiordani
    - lmoresi
